### ISSUE TITLE
:bind child naar parent werkt niet bij toggle

### ISSUE THREAD

**Issue by RaevensRobbe** [RaevensRobbe/Vliegtuigreservatie#2]
Dag @MLoth

Ik wil graag op mijn SelectLocation de togglestate aanpassen naar false als ik op de radiobutton geklikt heb zodat de selectLocation sluit. Normaal gezien op :bind als de variabele aangepast wordt in de child zal deze automatisch aangepast worden in de parent (dit werkt met departureCity en departureCountry maar niet met de toggle) Ik heb dit opdezelfde manier gedaan in de SelectTravelers waar dit wel werkt. De variabele past wel aan maar niet in de parent, ik heb al verschillende manieren geprobeerd om dit op te lossen maar geen enkele van deze lossen dit op. Wat mij wel opgevallen is dat als ik op de radiobutton klik ik 2x mijn console.log krijg.

dit is op volgende branch: [feature/flightSearchLocations](https://github.com/RaevensRobbe/Vliegtuigreservatie/tree/feature/flightSearchLocations)

FlightSearch.svelte:
- [In de script tag](https://github.com/RaevensRobbe/Vliegtuigreservatie/blob/feature/flightSearchLocations/Frontend/src/components/FlightSearch.svelte#L9)
- [Lijnen 92 - 98](https://github.com/RaevensRobbe/Vliegtuigreservatie/blob/feature/flightSearchLocations/Frontend/src/components/FlightSearch.svelte#L92)

SelectLocation.svelte
- [In de script tag](https://github.com/RaevensRobbe/Vliegtuigreservatie/blob/feature/flightSearchLocations/Frontend/src/components/flightSearchComponents/SelectLocation.svelte#L8)
- [Lijnen 206 - 229](https://github.com/RaevensRobbe/Vliegtuigreservatie/blob/feature/flightSearchLocations/Frontend/src/components/flightSearchComponents/SelectLocation.svelte#L206)

Op de travelers page kan je een voorbeeld zien op:
- [In de script tag](https://github.com/RaevensRobbe/Vliegtuigreservatie/blob/feature/flightSearchLocations/Frontend/src/components/flightSearchComponents/SelectTravelers.svelte#L6)
- [Op lijnen 96 - 100](https://github.com/RaevensRobbe/Vliegtuigreservatie/blob/feature/flightSearchLocations/Frontend/src/components/flightSearchComponents/SelectTravelers.svelte#L96)

**Comment by MLoth** [comment]
Still an issue?

**Comment by RaevensRobbe** [comment]
Ja, ik heb ondertussen andere componenten gemaakt en deze eventjes langs de kant geschoven aangezien ik hem wel kan sluiten door op de departure city en country bovenaan te klikken. Maar zou het liefst hebben dat ik deze kan sluiten als ik op de radiobutton van een city klik.

**Comment by MLoth** [comment]
https://github.com/testing-library/svelte-testing-library/issues/29 misschien omdat het een ander event is dat gebruikt wordt, dan je verwacht? Je wenst hier ook een change event en niet echt het input event.

**Comment by RaevensRobbe** [comment]
Issue solved: had verkeerde variabele doorgegeven en ik las er altijd over 🤦‍♂️
door het op te lossen kreeg ik wel andere problemen maar aan de hand van de value mee te geven aan een functie kon ik deze oplossen.
