### ISSUE TITLE
Cors error

### ISSUE THREAD

**Issue by DemetsJelle** [RaevensRobbe/Vliegtuigreservatie#3]
![250247630_172964008373861_1422683745137591026_n](https://user-images.githubusercontent.com/55786744/139664170-9ba1f763-7987-47c1-a378-a8b1f2d48ba4.png)

Bij Post request krijg ik deze error.

dit is op volgende branch: [feature/login]
(https://github.com/RaevensRobbe/Vliegtuigreservatie/tree/feature/login)

Ik probeerde het op te lossen door cors te importeren en dan app.use(cors) maar dit ging nog steeds niet.
Daarna probeerde ik het met een oplossing die ik gebruikte in het eerste labo toen ik ook dit probleem had maar ook dit werkte niet.

In app.ts: [Deze functie](https://github.com/RaevensRobbe/Vliegtuigreservatie/blob/feature/login/Backend/server/app.ts#L47)

**Comment by christophe-laprudence-howest** [comment]
Dag Jelle,
Het was een typo in je code als je de header manueel zet.
Het is Acce**ss**-Control-.... en niet Acce**s**-Control-....

Bij het gebruik van de import van cors (zoals ik het gedaan heb in de commit op je branch). Was je (denk ik) de cors package vergeten installeren. (Je installeerde enkel de @types/cors).
Ze zijn beide nodig:
npm install cors
npm install @types/cors

vergeet dan wel niet de haakjes te noteren bij je middleware
app.use(cors**()**)
